<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-15T15:01:22 ADT" name="Default suite" finished-at="2024-07-15T15:01:53 ADT" duration-ms="31565">
    <groups>
    </groups>
    <test started-at="2024-07-15T15:01:22 ADT" name="Default test" finished-at="2024-07-15T15:01:53 ADT" duration-ms="31565">
      <class name="com.taskmanagerplus.tests.TaskSearchTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.taskmanagerplus.tests.TaskSearchTest@5f9edf14]" started-at="2024-07-15T15:01:22 ADT" name="beforeSuite" finished-at="2024-07-15T15:01:22 ADT" duration-ms="270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:com.taskmanagerplus.tests.TaskSearchTest@5f9edf14]" started-at="2024-07-15T15:01:22 ADT" name="setUpClass" finished-at="2024-07-15T15:01:22 ADT" duration-ms="667" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.taskmanagerplus.tests.TaskSearchTest@5f9edf14]" started-at="2024-07-15T15:01:22 ADT" name="setUp" finished-at="2024-07-15T15:01:26 ADT" duration-ms="3303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="pagination_shouldWorkCorrectly()[pri:0, instance:com.taskmanagerplus.tests.TaskSearchTest@5f9edf14]" started-at="2024-07-15T15:01:26 ADT" name="pagination_shouldWorkCorrectly" finished-at="2024-07-15T15:01:53 ADT" duration-ms="26781" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The first task on the second page should be a task from the inserted test data. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The first task on the second page should be a task from the inserted test data. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.taskmanagerplus.tests.TaskSearchTest.pagination_shouldWorkCorrectly(TaskSearchTest.java:409)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pagination_shouldWorkCorrectly -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.taskmanagerplus.tests.TaskSearchTest@5f9edf14]" started-at="2024-07-15T15:01:53 ADT" name="tearDown" finished-at="2024-07-15T15:01:53 ADT" duration-ms="258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.taskmanagerplus.tests.TaskSearchTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
